### ISSUE TITLE
Failed in Ubuntu 20.04

### ISSUE THREAD

**Issue by arko-create** [jbehley/point_labeler#74]
[build] Found 3 packages in 0.0 seconds.                                                                                            
Traceback (most recent call last):
  File "/usr/local/bin/catkin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/commands/catkin.py", line 260, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 379, in main
    return build_isolated_workspace(
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 329, in build_isolated_workspace
    packages_to_be_built, packages_to_be_built_deps, all_packages = determine_packages_to_be_built(
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 81, in determine_packages_to_be_built
    ordered_packages = topological_order_packages(workspace_packages)
  File "/usr/lib/python3/dist-packages/catkin_pkg/topological_order.py", line 191, in topological_order_packages
    pkg.evaluate_conditions(os.environ)
  File "/usr/lib/python3/dist-packages/catkin_pkg/package.py", line 212, in evaluate_conditions
    conditional.evaluate_condition(context)
  File "/usr/lib/python3/dist-packages/catkin_pkg/package.py", line 369, in evaluate_condition
    self.evaluated_condition = evaluate_condition(self.condition, context)
  File "/usr/lib/python3/dist-packages/catkin_pkg/condition.py", line 23, in evaluate_condition
    expr = _get_condition_expression()
  File "/usr/lib/python3/dist-packages/catkin_pkg/condition.py", line 44, in _get_condition_expression
    _condition_expression = pp.operatorPrecedence(
AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'
❯ sudo apt install git libeigen3-dev libboost-all-dev qtbase5-dev libglew-dev catkin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
catkin is already the newest version (0.8.0-1ubuntu2).
libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libeigen3-dev is already the newest version (3.3.7-2).
libglew-dev is already the newest version (2.1.0-4).
git is already the newest version (1:2.25.1-1ubuntu3.11).
qtbase5-dev is already the newest version (5.12.8+dfsg-0ubuntu2.1).
The following packages were automatically installed and are no longer required:
  bridge-utils python3-cached-property python3-docker python3-dockerpty python3-docopt python3-importlib-metadata
  python3-jsonschema python3-more-itertools python3-pyrsistent python3-texttable python3-websocket python3-zipp ubuntu-fan
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.

**Comment by arko-create** [comment]
I have a Ubuntu 20.04 machine.
I followed the steps mentioned in Build process but when I try to build the project it fails with the above message. 
Let me know if I am missing out on something.

**Comment by jbehley** [comment]
it seems like that `catkin` is the problem that uses something form a package that doesn't exist anymore (maybe got deprecated and now removed: see also https://github.com/pyparsing/pyparsing/issues/327)

A work around would be to install a prior version `pyparsing`, e.g., `pip install pyparsing==2.4.7`. This was installed on my system and with this `catkin build` seems to work (ed).

As mentioned in a different issues; we have a pure `cmake`-based build in the making, but have to invest some more time to make the `glow` part `cmake`-compatible. I cannot promise to provide

**Comment by jbehley** [comment]
We have now a cmake-only build that should resolve the problem. If you are still interested, you can give it now a try.

If you still have issues, please re-open the issue again.
